# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-page_attachments-extension}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Cribbs"]
  s.date = %q{2010-06-28}
  s.description = %q{Page Attachments adds support for file uploads realized as attachments to individual pages. Attachments can have an order via acts_as_list, a title, a description and various metadata fields as provided by AttachmentFu.}
  s.email = %q{radiant@radiantcms.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "HELP.md",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/admin/page_attachments_controller.rb",
     "app/helpers/admin/page_attachments_helper.rb",
     "app/models/page_attachment.rb",
     "app/models/page_attachment_associations.rb",
     "app/models/page_attachment_tags.rb",
     "app/models/page_attachments_interface.rb",
     "app/views/admin/page_attachments/edit.html.haml",
     "app/views/admin/page_attachments/grid.html.haml",
     "app/views/admin/page_attachments/index.html.haml",
     "app/views/admin/pages/_attachment.html.erb",
     "app/views/admin/pages/_attachment.html.haml",
     "app/views/admin/pages/_attachments_box.html.haml",
     "db/migrate/001_create_page_attachments_extension_schema.rb",
     "db/migrate/002_add_page_attachments_fields.rb",
     "features/attachments.feature",
     "features/step_definitions/attachment_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "lib/difference_test_helper.rb",
     "lib/radiant-page_attachments-extension.rb",
     "lib/tasks/page_attachments_extension_tasks.rake",
     "page_attachments_extension.rb",
     "public/images/admin/drag_order.png",
     "public/images/admin/page_attachments/move_higher.png",
     "public/images/admin/page_attachments/move_lower.png",
     "public/images/admin/page_attachments/pdf-icon.png",
     "public/javascripts/admin/lowpro.js",
     "public/javascripts/admin/page_attachments.js",
     "public/stylesheets/admin/page_attachments.css",
     "public/stylesheets/page_attachments.css",
     "radiant-page_attachments-extension.gemspec",
     "spec/controllers/pages_controller_spec.rb",
     "spec/datasets/page_attachments_dataset.rb",
     "spec/fixtures/foo.txt",
     "spec/fixtures/rails.png",
     "spec/models/observe_page_attachments_spec.rb",
     "spec/models/page_attachment_spec.rb",
     "spec/models/page_attachment_tags_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "vendor/plugins/acts_as_list/README",
     "vendor/plugins/acts_as_list/init.rb",
     "vendor/plugins/acts_as_list/lib/active_record/acts/list.rb",
     "vendor/plugins/acts_as_list/test/list_test.rb",
     "vendor/plugins/attachment_fu/CHANGELOG",
     "vendor/plugins/attachment_fu/LICENSE",
     "vendor/plugins/attachment_fu/README",
     "vendor/plugins/attachment_fu/Rakefile",
     "vendor/plugins/attachment_fu/amazon_s3.yml.tpl",
     "vendor/plugins/attachment_fu/init.rb",
     "vendor/plugins/attachment_fu/install.rb",
     "vendor/plugins/attachment_fu/lib/geometry.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/backends/cloud_file_backend.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/backends/db_file_backend.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/backends/file_system_backend.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/backends/s3_backend.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/processors/core_image_processor.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/processors/gd2_processor.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/processors/image_science_processor.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/processors/mini_magick_processor.rb",
     "vendor/plugins/attachment_fu/lib/technoweenie/attachment_fu/processors/rmagick_processor.rb",
     "vendor/plugins/attachment_fu/rackspace_cloudfiles.yml.tpl",
     "vendor/plugins/attachment_fu/test/backends/db_file_test.rb",
     "vendor/plugins/attachment_fu/test/backends/file_system_test.rb",
     "vendor/plugins/attachment_fu/test/backends/remote/cloudfiles_test.rb",
     "vendor/plugins/attachment_fu/test/backends/remote/s3_test.rb",
     "vendor/plugins/attachment_fu/test/base_attachment_tests.rb",
     "vendor/plugins/attachment_fu/test/basic_test.rb",
     "vendor/plugins/attachment_fu/test/database.yml",
     "vendor/plugins/attachment_fu/test/extra_attachment_test.rb",
     "vendor/plugins/attachment_fu/test/fixtures/attachment.rb",
     "vendor/plugins/attachment_fu/test/fixtures/files/fake/rails.png",
     "vendor/plugins/attachment_fu/test/fixtures/files/foo.txt",
     "vendor/plugins/attachment_fu/test/fixtures/files/rails.png",
     "vendor/plugins/attachment_fu/test/geometry_test.rb",
     "vendor/plugins/attachment_fu/test/processors/core_image_test.rb",
     "vendor/plugins/attachment_fu/test/processors/gd2_test.rb",
     "vendor/plugins/attachment_fu/test/processors/image_science_test.rb",
     "vendor/plugins/attachment_fu/test/processors/mini_magick_test.rb",
     "vendor/plugins/attachment_fu/test/processors/rmagick_test.rb",
     "vendor/plugins/attachment_fu/test/schema.rb",
     "vendor/plugins/attachment_fu/test/test_helper.rb",
     "vendor/plugins/attachment_fu/test/validation_test.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/color.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/effects.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/perspective.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/quality.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/scale.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/filters/watermark.rb",
     "vendor/plugins/attachment_fu/vendor/red_artisan/core_image/processor.rb"
  ]
  s.homepage = %q{http://github.com/radiant/radiant-page-attachments-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds page-attachment-style asset management.}
  s.test_files = [
    "spec/controllers/pages_controller_spec.rb",
     "spec/datasets/page_attachments_dataset.rb",
     "spec/models/observe_page_attachments_spec.rb",
     "spec/models/page_attachment_spec.rb",
     "spec/models/page_attachment_tags_spec.rb",
     "spec/models/page_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

